# Day 01

In [1]:
from numba import cuda
import numpy as np

## Numba CUDA 101

In [2]:
@cuda.jit
def increment_by_one(an_array):
    pos = cuda.grid(1)
    if pos < an_array.size:
        an_array[pos] += 1

In [3]:
input_array = np.arange(100)
input_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
threadsperblock = 32
threadsperblock

32

In [5]:
blockspergrid = (input_array.size + (threadsperblock - 1)) // threadsperblock
blockspergrid

4

In [6]:
increment_by_one[blockspergrid, threadsperblock](input_array)

In [7]:
input_array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [8]:
increment_by_one[blockspergrid, threadsperblock](input_array)

In [9]:
input_array

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101])

### Get Pos

In [10]:
@cuda.jit
def get_pos(an_array):
    pos = cuda.grid(1)
    an_array[pos] = pos

In [11]:
pos_array = np.zeros(100)
pos_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
threadsperblock = 32
blockspergrid = (pos_array.size + (threadsperblock - 1)) // threadsperblock

In [13]:
get_pos[blockspergrid, threadsperblock](pos_array)

In [14]:
pos_array

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

### Manual memory copy

In [15]:
cpu_pos_array = np.zeros(100)
cpu_pos_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
gpu_pos_array = cuda.to_device(cpu_pos_array)
gpu_pos_array

In [17]:
get_pos[blockspergrid, threadsperblock](gpu_pos_array)

In [18]:
returned_cpu_pos_array = gpu_pos_array.copy_to_host()
returned_cpu_pos_array

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95., 96., 97., 98., 99.])

## Expense report - Part 1

In [19]:
with open('input.txt') as f:
    lines=f.readlines()
    expenses = np.asarray(lines, dtype=float)
expenses

array([1130., 1897., 1850., 1218., 1198., 1761., 1082., 1742., 1821.,
       1464., 1834., 1413., 1917., 1746., 1954., 1942., 1560., 1227.,
       1852., 1976., 1773., 1404., 1824., 1011., 1532., 1306., 1819.,
       1739., 1540., 1973., 1436., 1196., 1176., 1856., 1332., 1617.,
       1895., 1749., 1718., 1536., 1811.,  113., 1008., 1908., 1799.,
       1914., 1603., 1782., 1980., 1228., 1838., 2006., 1953., 1846.,
       1903., 1470., 1774., 1599., 1446., 1324., 1054., 1952., 1928.,
       1997., 1764., 1943., 1932., 1615., 1428., 1036.,  721., 1097.,
       1998., 1033., 1892., 1904., 1803., 1825., 1370., 1836., 1853.,
       1963., 1469., 1385.,  246., 1987., 1153.,  178., 1790., 1927.,
       1139., 1865., 1804., 1974., 1235., 1681., 1185., 2009., 1894.,
       1141., 1203., 1808., 1867., 1274., 1891., 1779., 1342., 1920.,
        851., 1994., 1975., 1979., 1880., 1647., 1365.,  448., 1119.,
       1256., 1212., 1268., 1878., 1805., 1889., 1870., 1906., 1959.,
       1898., 1305.,

In [20]:
output_array = np.zeros(expenses.shape)
output_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
@cuda.jit
def calculate_2020(input_array, output_array):
    pos = cuda.grid(1)
    for i in range(len(expenses)):
        if pos == i:
            continue
        if input_array[pos] + input_array[i] == 2020:
            output_array[pos] = input_array[pos] * input_array[i]

In [22]:
threadsperblock = 32
blockspergrid = (expenses.size + (threadsperblock - 1)) // threadsperblock

In [23]:
calculate_2020[blockspergrid, threadsperblock](expenses, output_array)

In [24]:
int(np.unique(output_array[np.where(output_array > 0)]))

436404

In [25]:
def calculate_day01_part1(input_filename):
    with open(input_filename) as f:
        lines=f.readlines()
        expenses = np.asarray(lines, dtype=float)
    output_array = np.zeros(expenses.shape)
    
    threadsperblock = 32
    blockspergrid = (expenses.size + (threadsperblock - 1)) // threadsperblock
    
    calculate_2020[blockspergrid, threadsperblock](expenses, output_array)
    
    return int(np.unique(output_array[np.where(output_array > 0)]))

In [26]:
calculate_day01_part1("input.txt")

436404

## Expense report - Part 2

In [27]:
@cuda.jit
def calculate_2020_2d(input_array, output_array):
    x_pos, y_pos = cuda.grid(2)
    if x_pos == y_pos:
        return
    if input_array[x_pos] + input_array[y_pos] == 2020:
        output_array[x_pos] = input_array[x_pos] * input_array[y_pos]

In [28]:
output_array = np.zeros(expenses.shape)
output_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
threadsperblock = (8, 8)
blockspergrid = (expenses.size + (threadsperblock[0] - 1)) // threadsperblock[0]
blockspergrid = (blockspergrid, blockspergrid)
blockspergrid

(25, 25)

In [30]:
calculate_2020_2d[blockspergrid, threadsperblock](expenses, output_array)
output_array

array([     0.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.,      0.,      0.,      0.,
       436404.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.,      0.,      0.,      0.,
       436404.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,     

In [31]:
@cuda.jit
def calculate_2020_3d(input_array, output_array):
    x_pos, y_pos, z_pos = cuda.grid(3)
    if x_pos == y_pos or x_pos == z_pos or z_pos == y_pos:
        return
    if input_array[x_pos] + input_array[y_pos] + input_array[z_pos] == 2020:
        output_array[x_pos] = input_array[x_pos] * input_array[y_pos] * input_array[z_pos]

def calculate_day01_part2(input_filename):
    output_array = np.zeros(expenses.shape)

    threadsperblock = (8, 8, 8)
    blockspergrid = (expenses.size + (threadsperblock[0] - 1)) // threadsperblock[0]
    blockspergrid = (blockspergrid, blockspergrid, blockspergrid)

    calculate_2020_3d[blockspergrid, threadsperblock](expenses, output_array)
    return int(np.unique(output_array[np.where(output_array > 0)]))

In [32]:
calculate_day01_part2("input.txt")

274879808