## Data reading

In [3]:
import numpy as np

In [7]:
with open("input.txt") as fh:
    tickets = np.asarray([np.asarray([ord(c) for c in row.strip()]) for row in fh.readlines()])
tickets

array([[70, 66, 66, ..., 82, 82, 76],
       [66, 66, 70, ..., 82, 82, 82],
       [66, 70, 66, ..., 76, 82, 82],
       ...,
       [66, 70, 66, ..., 82, 82, 82],
       [70, 66, 66, ..., 82, 76, 76],
       [70, 66, 70, ..., 82, 82, 76]])

In [9]:
comparisons = np.asarray([ord(c) for c in "FBLR"])
comparisons

array([70, 66, 76, 82])

## Part 1

In [10]:
from numba import cuda

In [26]:
@cuda.jit
def calculate_ticket_numbers(tickets, comparisons, output):
    pos = cuda.grid(1)
    front, back, left, right = comparisons
    if pos < len(tickets):
        instructions = tickets[pos]
        row_lower, row_upper = 0, 127
        col_lower, col_upper = 0, 7
        for i in instructions:
            if i == front:
                print("front")
                row_upper = (row_lower + (row_upper - 1)) / 2
            if i == back:
                print("back")
                row_lower = (row_lower + (row_upper + 1)) / 2
            if i == left:
                print("left")
                col_upper = (col_lower + (col_upper - 1)) / 2
            if i == right:
                print("right")
                col_lower = (col_lower + (col_upper + 1)) / 2

        output[pos] = (row_lower * 8) + col_lower

In [27]:
threadsperblock = 128
blockspergrid = (len(tickets) + (threadsperblock - 1)) // threadsperblock

In [28]:
output = np.zeros(len(tickets))
calculate_ticket_numbers[blockspergrid, threadsperblock](tickets, comparisons, output)
output

array([422., 815., 707., 137., 765., 274., 755., 238., 362., 783., 511.,
       200., 775., 596., 653., 450., 690., 575., 310., 833., 444., 813.,
       524., 799., 308., 502., 834., 701., 447., 736., 512., 650., 441.,
       556., 146., 333., 793., 583., 312., 644., 358., 696., 677., 418.,
       537., 479., 451., 243., 518., 770., 597., 249., 300., 715., 529.,
       484., 457., 624., 184., 835., 322., 614., 347., 220., 212., 558.,
       756., 552., 568., 494., 716., 709., 240., 204., 163., 478., 187.,
       647., 623., 540., 567., 557., 231., 598., 253., 430., 250., 223.,
       625., 167., 718., 729., 461., 609., 407., 139., 126., 425., 487.,
       122., 462., 722., 438., 437., 820., 777., 144., 206., 392., 121.,
       456., 177., 434., 821., 381., 678., 728., 382., 172., 630., 589.,
       363., 194., 797., 225., 287., 622., 708., 365., 480., 209., 629.,
       572., 682., 519., 350., 662., 259., 246., 255., 670., 786., 493.,
       663., 236., 152., 746., 633., 180., 571., 83

In [29]:
max(output)

838.0

## Part 2

In [33]:
all_seats = np.arange(min(output), max(output))
all_seats

array([ 95.,  96.,  97.,  98.,  99., 100., 101., 102., 103., 104., 105.,
       106., 107., 108., 109., 110., 111., 112., 113., 114., 115., 116.,
       117., 118., 119., 120., 121., 122., 123., 124., 125., 126., 127.,
       128., 129., 130., 131., 132., 133., 134., 135., 136., 137., 138.,
       139., 140., 141., 142., 143., 144., 145., 146., 147., 148., 149.,
       150., 151., 152., 153., 154., 155., 156., 157., 158., 159., 160.,
       161., 162., 163., 164., 165., 166., 167., 168., 169., 170., 171.,
       172., 173., 174., 175., 176., 177., 178., 179., 180., 181., 182.,
       183., 184., 185., 186., 187., 188., 189., 190., 191., 192., 193.,
       194., 195., 196., 197., 198., 199., 200., 201., 202., 203., 204.,
       205., 206., 207., 208., 209., 210., 211., 212., 213., 214., 215.,
       216., 217., 218., 219., 220., 221., 222., 223., 224., 225., 226.,
       227., 228., 229., 230., 231., 232., 233., 234., 235., 236., 237.,
       238., 239., 240., 241., 242., 243., 244., 24

In [35]:
for seat in all_seats:
    if seat not in output and seat - 1 in output and seat + 1 in output:
        print(seat)

714.0
